In [114]:
import pandas as pd
df=pd.read_csv('reqfiles/Fake.csv')
df.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [115]:
df=df.drop('date',axis=1)

In [116]:
df.head()

,title,text,subject
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News

In [117]:
df['target']=1
df.head()

,title,text,subject,target
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,1
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,1
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,1
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,1
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,1

In [118]:
df.shape
df=df.drop('subject',axis=1)
df.shape

(23481, 3)

In [119]:
df2=pd.read_csv('reqfiles/True.csv')
df2=df2.drop('subject',axis=1)
df2=df2.drop('date',axis=1)
df2['target']=0
df2.shape

(21417, 3)

In [120]:
#combining both the dataframes(true and Fake) into a single dataframe df
df = pd.concat([df, df2], axis=0)
df.reset_index(drop=True, inplace=True)
df = df.sample(frac=1, random_state=42).reset_index(drop=True)
df.head()

,title,text,target
0,Ben Stein Calls Out 9th Circuit Court: Committ...,"21st Century Wire says Ben Stein, reputable pr...",1
1,Trump drops Steve Bannon from National Securit...,WASHINGTON (Reuters) - U.S. President Donald T...,0
2,Puerto Rico expects U.S. to lift Jones Act shi...,(Reuters) - Puerto Rico Governor Ricardo Rosse...,0
3,OOPS: Trump Just Accidentally Confirmed He Le...,"On Monday, Donald Trump once again embarrassed...",1
4,Donald Trump heads for Scotland to reopen a go...,"GLASGOW, Scotland (Reuters) - Most U.S. presid...",0

In [121]:
# Basic column info and data types
print("Shape:", df.shape)
print("\nData types:")
print(df.dtypes)

# Check NaN values
print("\nNaN values per column:")
print(df.isna().sum())
print(df.isnull().sum())

# Check empty strings "" and blank-space strings like " "
print("\nEmpty or blank-space values per column:")
for col in df.columns:
    if df[col].dtype == "str":
        blank_count = df[col].astype(str).str.strip().eq("").sum()
        print(f"{col}: {blank_count}")
    else:
        print(f"{col}: not a text column")

Shape: (44898, 3)

Data types:
title       str
text        str
target    int64
dtype: object

NaN values per column:
title     0
text      0
target    0
dtype: int64
title     0
text      0
target    0
dtype: int64

Empty or blank-space values per column:
title: 0
text: 631
target: not a text column

In [122]:
blank_text_rows = df[df['text'].astype(str).str.strip().eq("")]
blank_text_rows.shape

(631, 3)

In [123]:
blank_text_rows.head()
blank_text_rows[blank_text_rows['target']==0].head()

                                title text  target
22891  Graphic: Supreme Court roundup            0

In [124]:
# Remove rows where text is empty or only spaces
df = df[~df["text"].astype(str).str.strip().eq("")].reset_index(drop=True)

df.shape

(44267, 3)

In [125]:
#confirmation to show that blank rows are not present in df anymore
blank_text_rows = df[df['text'].astype(str).str.strip().eq("")]
blank_text_rows.shape
blank_text_rows.head()

Empty DataFrame
Columns: [title, text, target]
Index: []

In [126]:
df.to_csv('reqfiles/AfterFE.csv',index=False)